//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace emplolist.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    public enum UserType
    {
        user,
        admin
    }

    public class LoginViewModel1
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public UserType UserType { get; set; }
    }
    public partial class emplolistEntities : DbContext
    {
        public emplolistEntities()
            : base("name=emplolistEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
